import React from 'react';

export default function ProofTrace({ trace, timestamp, verified }) {
  if (!trace || trace.length === 0) return null;

  return (
    <div className="mt-8 border border-blue-200 dark:border-blue-900 rounded-xl overflow-hidden bg-blue-50/30 dark:bg-blue-900/10">
      <div className="bg-blue-100 dark:bg-blue-900/30 px-6 py-4 flex justify-between items-center border-b border-blue-200 dark:border-blue-800">
        <div>
          <h3 className="text-lg font-bold text-blue-900 dark:text-blue-100 flex items-center gap-2">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            System Proof
          </h3>
          <p className="text-xs text-blue-700 dark:text-blue-300">
            Generated on {new Date(timestamp).toLocaleString()}
          </p>
        </div>
        {verified && (
          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300 border border-green-200 dark:border-green-800">
            Verified Logic
          </span>
        )}
      </div>
      
      <div className="p-6 space-y-6">
        <div className="relative">
          {/* Vertical line */}
          <div className="absolute left-4 top-2 bottom-2 w-0.5 bg-blue-200 dark:bg-blue-800"></div>
          
          <div className="space-y-8">
            {trace.map((step, index) => (
              <div key={index} className="relative pl-10">
                {/* Dot */}
                <div className="absolute left-2.5 top-1.5 w-3.5 h-3.5 rounded-full border-2 border-blue-500 bg-white dark:bg-slate-900 z-10"></div>
                
                <div>
                  <div className="flex justify-between items-start mb-1">
                    <h4 className="font-bold text-slate-900 dark:text-slate-100">{step.rule}</h4>
                    <span className={`text-xs font-mono px-1.5 py-0.5 rounded ${step.impact >= 0 ? 'bg-green-50 text-green-700 dark:bg-green-900/20 dark:text-green-400' : 'bg-red-50 text-red-700 dark:bg-red-900/20 dark:text-red-400'}`}>
                      {step.impact > 0 ? '+' : ''}{step.impact}
                    </span>
                  </div>
                  <p className="text-sm text-slate-600 dark:text-slate-400 mb-2">{step.description}</p>
                  <div className="bg-white/50 dark:bg-black/20 p-3 rounded-lg border border-blue-100 dark:border-blue-900/50">
                    <p className="text-xs italic text-slate-500 dark:text-slate-500">
                      " {step.reasoning} "
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      
      <div className="bg-blue-50/50 dark:bg-blue-950/20 px-6 py-4 border-t border-blue-100 dark:border-blue-900">
        <p className="text-xs text-center text-slate-500 dark:text-slate-400">
          This proof is generated by the SEO-Uplift Prover Engine using formal verification rules.
          No black-box AI was used for these calculations.
        </p>
      </div>
    </div>
  );
}
